// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1V59vSRYk7BQrS5XY3aYdTtj4ELZv_E',
    appId: '1:1029275813190:web:1bc6db755f6ccc9df41147',
    messagingSenderId: '1029275813190',
    projectId: 'tnsnacks',
    authDomain: 'tnsnacks.firebaseapp.com',
    storageBucket: 'tnsnacks.firebasestorage.app',
    measurementId: 'G-P9X5FSYX0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9g4cm9bBPUeKOLE8lWNJbkMIHtYCU1Zs',
    appId: '1:1029275813190:android:983b1f654d471b17f41147',
    messagingSenderId: '1029275813190',
    projectId: 'tnsnacks',
    storageBucket: 'tnsnacks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANioeDKIlOlq2y6XdFu79sYkx_7-oyp2w',
    appId: '1:1029275813190:ios:becfb0f96cfdfb93f41147',
    messagingSenderId: '1029275813190',
    projectId: 'tnsnacks',
    storageBucket: 'tnsnacks.firebasestorage.app',
    iosBundleId: 'com.example.tn70snacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANioeDKIlOlq2y6XdFu79sYkx_7-oyp2w',
    appId: '1:1029275813190:ios:becfb0f96cfdfb93f41147',
    messagingSenderId: '1029275813190',
    projectId: 'tnsnacks',
    storageBucket: 'tnsnacks.firebasestorage.app',
    iosBundleId: 'com.example.tn70snacks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa1V59vSRYk7BQrS5XY3aYdTtj4ELZv_E',
    appId: '1:1029275813190:web:4a8e3da3a8a47ca5f41147',
    messagingSenderId: '1029275813190',
    projectId: 'tnsnacks',
    authDomain: 'tnsnacks.firebaseapp.com',
    storageBucket: 'tnsnacks.firebasestorage.app',
    measurementId: 'G-FGXBGXTHM8',
  );
}
